<?php
/**
 * Created by IntelliJ IDEA.
 * User: neo
 * Date: 15/11/23
 * Time: 下午3:02
 */

namespace app\models;


use yii\db\ActiveRecord;

class Country extends ActiveRecord
{

	public static function tableName()
	{
		return 'country';//return parent::tableName(); // TODO: Change the autogenerated stub
	}
}