<?php
/**
 * Created by IntelliJ IDEA.
 * User: neo
 * Date: 15/11/23
 * Time: 上午2:41
 */

namespace app\models;


use yii\base\Model;

class EntryForm extends Model
{
	public $name;

	public $email;

	public function rules()
	{
		return [
			[['name','email'],'required'],
			['email','email'],
		];
	//	return parent::rules(); // TODO: Change the autogenerated stub
	}

}